version = 1

test_patterns = [
    "docs/.vuepress",
    "config.js"
]

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "terraform"
enabled = true

[[transformers]]
name = "gofmt"
enabled = true

[[transformers]]
name = "yapf"
enabled = true

[[transformers]]
name = "black"
enabled = true